### ISSUE TITLE
bug: pygame cannot play sound

### ISSUE THREAD

**Issue by mxmaxime** [mxmaxime/mx-tech-house#126]
It was working well, but it doesn't now. I don't have any clue why.

```
sound_1   | ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
sound_1   | ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
sound_1   | ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
sound_1   | ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
sound_1   | ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
sound_1   | ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
sound_1   | ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
sound_1   | ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default
sound_1   | Traceback (most recent call last):
sound_1   |   File "sound.py", line 5, in <module>
sound_1   |     from sound.run_sound import run_sound_factory
sound_1   |   File "/usr/src/app/sound/run_sound.py", line 2, in <module>
sound_1   |     from sound.sound import Sound
sound_1   |   File "/usr/src/app/sound/sound.py", line 27, in <module>
sound_1   |     Sound().alarm()
sound_1   |   File "/usr/src/app/sound/sound.py", line 8, in __init__
sound_1   |     pygame.mixer.init()
sound_1   | pygame.error: No available audio device
```

**Comment by mxmaxime** [comment]
It was missing the line `privileged: true` for the service `sound`. The bug was introduced when I split camera and sound services.
